// <auto-generated />
using System;
using KangaApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KangaApp.Migrations
{
    [DbContext(typeof(KangaContext))]
    [Migration("20220905102101_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KangaApp.Models.Client", b =>
                {
                    b.Property<int>("ProductNumber")
                        .HasColumnType("int")
                        .HasColumnName("Product Number");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Client Address");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Client Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone Number");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Product Name");

                    b.HasKey("ProductNumber");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("KangaApp.Models.Product", b =>
                {
                    b.Property<int>("ProductNumber")
                        .HasColumnType("int")
                        .HasColumnName("Product Number");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Product Name");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductNumber");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("KangaApp.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .HasColumnType("int")
                        .HasColumnName("Vendor Id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone Number");

                    b.Property<int>("ProductNumber")
                        .HasColumnType("int")
                        .HasColumnName("Product Number");

                    b.Property<string>("VendorAddress")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Vendor Address");

                    b.Property<string>("VendorEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Vendor Email");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Vendor Name");

                    b.HasKey("VendorId");

                    b.ToTable("Vendor", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
